### ISSUE TITLE
Change syntax to augment position: type;

### ISSUE THREAD

**Issue by madeleineostoja** [seaneking/postcss-position#4]
Rethinking the API for this plugin. It seems to make more sense to augment the existing `property` declaration with shorthand offsets, rather than create three whole new declarations. Probably more intuitive for users, as it stays closer to spec CSS (though one could argue the existing is easier as it’s the same as other layout props like margin/padding). Also makes it easier to quickly rip out the plugin in the future if need be.

So instead of 

``` css
absolute: 0;
relative: 20% auto;
```

We’d have

``` css
position: absolute 0;
position: relative 20% auto;
```

Both compiling to the same thing.

**Comment by madeleineostoja** [comment]
Of course could alias to both… Though would prefer to keep a single syntax for clarity/simplicity

**Comment by bedeoverend** [comment]
+1 I prefer the new proposed syntax as it's closer to spec, which feels much more appropriate, particularly for PostCSS. Perhaps deprecate the old syntax, but keep support for it for awhile?

**Comment by bedeoverend** [comment]
Unless my understanding of CSS is wrong, every declaration is independent of another, i.e. two different declarations won't affect each either, unless you're using a shorthand (e.g. `background`, `background-color`) but the current syntax doesn't follow it, one declaration will override another. I think that's the biggest reason why I'm keen for the new syntax

**Comment by madeleineostoja** [comment]
Great point. Didn’t even think of that. I think that seals the deal, will go ahead with the new syntax and deprecate the old.

**Comment by madeleineostoja** [comment]
Fixed in https://github.com/seaneking/postcss-position/commit/17a92bb84132392fe7733012443ed9d5872f7fe3
